function test_lattice_hifi_two_step_fusion()
%TEST_LATTICE_HIFI_TWO_STEP_FUSION Guard optional two-step Wiener fusion.

testDir = fileparts(mfilename('fullpath'));
coreDir = fileparts(testDir);
addpath(fullfile(coreDir, 'functions'));

params = defaultLatticeSIMParams();
assert(isfield(params, 'fusionMode'), ...
    'Default params should expose a fusionMode switch.');
assert(strcmp(char(params.fusionMode), 'single-step'), ...
    'Default fusionMode should preserve the existing single-step fusion.');
assert(isfield(params, 'wienerW1') && params.wienerW1 == 1.2, ...
    'Default params should expose the HiFi-style W1 constant.');
assert(isfield(params, 'wienerW2') && params.wienerW2 == 0.1, ...
    'Default params should expose the HiFi-style W2 constant.');
assert(isfield(params, 'hifiDenominatorScaleW1') && params.hifiDenominatorScaleW1 == 1.0, ...
    'Default params should expose the HiFi-style W1 denominator scale.');
assert(isfield(params, 'hifiDenominatorScaleW2') && params.hifiDenominatorScaleW2 == 1.0, ...
    'Default params should expose the HiFi-style W2 denominator scale.');
assert(isfield(params, 'hifiCenterDenominatorWeight') && ...
    params.hifiCenterDenominatorWeight == 0.5, ...
    'Default params should expose the HiFi centered denominator half weight.');
assert(isfield(params, 'hifiW1SidebandAttenuationScale') && ...
    params.hifiW1SidebandAttenuationScale == 1.0, ...
    'Default params should expose the HiFi W1 sideband attenuation scale.');
assert(isfield(params, 'hifiW2CenterAttenuationScale') && ...
    params.hifiW2CenterAttenuationScale == 1.05, ...
    'Default params should expose the HiFi W2 center attenuation scale.');
assert(isfield(params, 'hifiW2SidebandAttenuationScale') && ...
    params.hifiW2SidebandAttenuationScale == 1.15, ...
    'Default params should expose the HiFi W2 sideband attenuation scale.');

params.pixelSizeNm = 97.5;
params.emissionWavelengthNm = 561;
params.NA = 1.42;
params.fusionMode = "hifi-two-step";
params.wienerW1 = 1.2;
params.wienerW2 = 0.1;
params.hifiDenominatorScaleW1 = 0.5;
params.hifiDenominatorScaleW2 = 0.25;
params.otfAttenuationEnabled = true;
params.otfAttenuationStrength = 0.30;
params.otfAttenuationFwhm = 0.40;

bands = makeFrequencyBands([40, 40]);
carriers.ksPixel = [6, 0];
carriers.ktPixel = [0, 7];
otf = buildLatticeOTF(40, 40, params);

[simImage, diagnostics] = combineLatticeSpectrum(bands, carriers, otf, params);

assert(strcmp(diagnostics.fusionMode, 'hifi-two-step'), ...
    'Diagnostics should record the active fusion mode.');
assert(isfield(diagnostics, 'spectrumAfterW1'), ...
    'Two-step fusion should expose the spectrum after W1.');
assert(isfield(diagnostics, 'spectrumAfterW2'), ...
    'Two-step fusion should expose the spectrum after W2.');
assert(isfield(diagnostics, 'wienerW1'), ...
    'Two-step fusion should expose the W1 filter.');
assert(isfield(diagnostics, 'wienerW2'), ...
    'Two-step fusion should expose the W2 filter.');
assert(isfield(diagnostics, 'wienerDenominatorW1'), ...
    'Two-step fusion should expose the W1 denominator.');
assert(isfield(diagnostics, 'wienerDenominatorW2'), ...
    'Two-step fusion should expose the W2 denominator.');
assert(isfield(diagnostics, 'hifiMask'), ...
    'Two-step fusion should expose the support mask used by both steps.');
assert(isfield(diagnostics, 'hifiOtf'), ...
    'Two-step fusion should expose the HiFi-style OTF numerator.');
assert(isfield(diagnostics, 'apodizationMask'), ...
    'Two-step fusion should expose the apodization numerator used by W2.');
assert(isfield(diagnostics, 'denominatorBandNames'), ...
    'Fusion diagnostics should name each HiFi-style denominator contribution.');
assert(isfield(diagnostics, 'denominatorW1Contributions'), ...
    'Fusion diagnostics should expose W1 denominator contributions by band.');
assert(isfield(diagnostics, 'denominatorW2Contributions'), ...
    'Fusion diagnostics should expose W2 denominator contributions by band.');
assert(isfield(diagnostics, 'nonAttenuatedOtfValues'), ...
    'Fusion diagnostics should expose the damped OTF before notch attenuation.');
assert(isfield(diagnostics, 'denominatorAttenuationMasksW1'), ...
    'Fusion diagnostics should expose W1 attenuation masks by band.');
assert(isfield(diagnostics, 'denominatorAttenuationMasksW2'), ...
    'Fusion diagnostics should expose W2 attenuation masks by band.');
assert(all(abs(diagnostics.hifiOtf(diagnostics.hifiMask > 0)) > 0), ...
    'The HiFi-style W1 numerator should cover the full expanded SIM support mask.');
assert(nnz(abs(diagnostics.hifiOtf) > 0) > nnz(abs(diagnostics.physicalOtfValues) > 0), ...
    'The HiFi-style W1 numerator should extend beyond the conventional centered OTF support.');
assert(max(abs(diagnostics.wienerDenominatorW1(:) - ...
    diagnostics.wienerDenominatorW1Base(:) * params.hifiDenominatorScaleW1)) < 1e-12, ...
    'W1 denominator scale should only affect the HiFi-style W1 denominator.');
assert(max(abs(diagnostics.wienerDenominatorW2(:) - ...
    diagnostics.wienerDenominatorW2Base(:) * params.hifiDenominatorScaleW2)) < 1e-12, ...
    'W2 denominator scale should only affect the HiFi-style W2 denominator.');

centerContributionIndex = find(strcmp(diagnostics.denominatorBandNames, 'C0+'), 1);
assert(~isempty(centerContributionIndex), ...
    'The HiFi-style denominator should keep the first centered OTF half contribution.');
center = floor(size(diagnostics.nonAttenuatedOtfValues) / 2) + 1;
centerBase = abs(diagnostics.nonAttenuatedOtfValues(center(1), center(2))) ^ 2;
centerW1 = diagnostics.denominatorW1Contributions{centerContributionIndex};
centerW2 = diagnostics.denominatorW2Contributions{centerContributionIndex};
centerAttW1 = diagnostics.denominatorAttenuationMasksW1{centerContributionIndex};
centerAttW2 = diagnostics.denominatorAttenuationMasksW2{centerContributionIndex};
expectedCenterAttW2 = 1 - params.otfAttenuationStrength / 1.05;
assert(abs(centerW1(center(1), center(2)) - 0.5 * centerBase) < 1e-12, ...
    'Each centered OTF denominator half should keep HiFi b==1 /2 weighting in W1.');
assert(abs(centerAttW1(center(1), center(2)) - 1) < 1e-12, ...
    'W1 should keep the centered denominator unattenuated like HiFi NoAtt b==1.');
assert(abs(centerAttW2(center(1), center(2)) - expectedCenterAttW2) < 1e-12, ...
    'W2 should apply the HiFi center attenuation strength scale of 1.05.');
assert(abs(centerW2(center(1), center(2)) - ...
    0.5 * centerBase * expectedCenterAttW2) < 1e-12, ...
    'Each centered OTF denominator half should use scaled center attenuation in W2.');

sideContributionIndex = find(strcmp(diagnostics.denominatorBandNames, 'CsPlus'), 1);
assert(~isempty(sideContributionIndex), ...
    'The HiFi-style denominator should include the S positive sideband contribution.');
sideBase = diagnostics.denominatorBaseOtfValues{sideContributionIndex};
sideW1 = diagnostics.denominatorW1Contributions{sideContributionIndex};
sideW2 = diagnostics.denominatorW2Contributions{sideContributionIndex};
sideAttW1 = diagnostics.denominatorAttenuationMasksW1{sideContributionIndex};
sideAttW2 = diagnostics.denominatorAttenuationMasksW2{sideContributionIndex};
[~, sideMaxIdx] = max(abs(sideBase(:)));
expectedSideW1 = abs(sideBase(sideMaxIdx)) ^ 2 * sideAttW1(sideMaxIdx);
expectedSideW2 = abs(sideBase(sideMaxIdx)) ^ 2 * sideAttW2(sideMaxIdx);
assert(abs(sideW1(sideMaxIdx) - expectedSideW1) < 1e-12, ...
    'W1 sideband denominator should square the non-attenuated OTF and multiply attenuation once.');
assert(abs(sideW2(sideMaxIdx) - expectedSideW2) < 1e-12, ...
    'W2 sideband denominator should square the non-attenuated OTF and multiply scaled attenuation once.');
assert(sideAttW2(sideMaxIdx) > sideAttW1(sideMaxIdx), ...
    'W2 sideband attenuation should use the weaker HiFi add-denominator scale of 1.15.');

expectedW1Base = zeros(size(diagnostics.wienerDenominatorW1Base));
expectedW2Base = zeros(size(diagnostics.wienerDenominatorW2Base));
for idx = 1:numel(diagnostics.denominatorW1Contributions)
    expectedW1Base = expectedW1Base + diagnostics.denominatorW1Contributions{idx};
    expectedW2Base = expectedW2Base + diagnostics.denominatorW2Contributions{idx};
end
assert(max(abs(expectedW1Base(:) - diagnostics.wienerDenominatorW1Base(:))) < 1e-12, ...
    'W1 denominator base should equal the sum of all HiFi-style component contributions.');
assert(max(abs(expectedW2Base(:) - diagnostics.wienerDenominatorW2Base(:))) < 1e-12, ...
    'W2 denominator base should equal the sum of all HiFi-style component contributions.');

expectedAfterW1 = diagnostics.fftDirectlyCombined .* ...
    diagnostics.wienerW1 .* diagnostics.hifiMask;
expectedSpectrum = expectedAfterW1 .* ...
    diagnostics.wienerW2 .* diagnostics.hifiMask;
scale = max(1, max(abs(expectedSpectrum(:))));
assert(max(abs(diagnostics.spectrumAfterW1(:) - expectedAfterW1(:))) / scale < 1e-12, ...
    'spectrumAfterW1 should equal fftDirectlyCombined .* W1 .* support mask.');
assert(max(abs(diagnostics.spectrumAfterW2(:) - expectedSpectrum(:))) / scale < 1e-12, ...
    'spectrumAfterW2 should equal spectrumAfterW1 .* W2 .* support mask.');
assert(max(abs(diagnostics.simSpectrum(:) - expectedSpectrum(:))) / scale < 1e-12, ...
    'Final SIM spectrum should equal fftDirectlyCombined .* W1 .* M .* W2 .* M.');
assert(max(abs(diagnostics.simSpectrum(:) - ...
    diagnostics.fftDirectlyCombined(:) .* diagnostics.wienerFilter(:) .* ...
    diagnostics.finalConfidenceMask(:) .* diagnostics.apodizationMask(:))) / scale > 1e-6, ...
    'HiFi two-step mode should not collapse back to the single-step confidence/apodization formula.');

weightedSum = zeros(size(diagnostics.fftDirectlyCombined));
for idx = 1:numel(diagnostics.fusionNumeratorContributions)
    weightedSum = weightedSum + diagnostics.fusionNumeratorContributions{idx};
end
assert(max(abs(weightedSum(:) - diagnostics.fftDirectlyCombined(:))) < 1e-10 * ...
    max(1, max(abs(diagnostics.fftDirectlyCombined(:)))), ...
    'The five OTF-weighted contributions should sum to fftDirectlyCombined.');

assert(all(isfinite(simImage(:))), 'SIM image must not contain NaN or Inf.');
assert(all(isfinite(diagnostics.simSpectrum(:))), 'SIM spectrum must not contain NaN or Inf.');
end

function bands = makeFrequencyBands(imageSize)
[x, y] = meshgrid(linspace(-1, 1, imageSize(2)), linspace(-1, 1, imageSize(1)));
base = exp(-10 * (x .^ 2 + y .^ 2));
spectrum = FFT2D(base, false);

bands.C0 = spectrum;
bands.CsPlus = 0.42 * spectrum .* exp(1i * 0.2);
bands.CsMinus = 0.39 * spectrum .* exp(-1i * 0.1);
bands.CtPlus = 0.36 * spectrum .* exp(1i * 0.3);
bands.CtMinus = 0.33 * spectrum .* exp(-1i * 0.25);
bands.domain = 'frequency';
end
